apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx 
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: cluster-pi.k8s 
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx 
          servicePort: http
